package com.google.android.tvlauncher.util.porting;

/**
 * Created by rockon999 on 2/23/18.
 */

public enum Reason {
    VARIABLE_REUSAGE,
    IF_ELSE_DECOMPILE_ERROR,
    VARIABLE_TERNARY_ERROR, SWITCH_COMPILE_ERROR, VARIABLE_NAMING_CLARITY, WHILE_TO_FOR, FOR_WHILE_MIXUP, IF_WHILE_MIXUP, HOT_MESS, API_CHANGE, UNKNOWN_COMPILE_ERROR
}
