package android.support.graphics.drawable;

import android.support.annotation.StyleableRes;

class AndroidResources
{
  public static final int FAST_OUT_LINEAR_IN = 17563663;
  public static final int FAST_OUT_SLOW_IN = 17563661;
  public static final int LINEAR_OUT_SLOW_IN = 17563662;
  static final int[] STYLEABLE_ANIMATED_VECTOR_DRAWABLE;
  static final int STYLEABLE_ANIMATED_VECTOR_DRAWABLE_DRAWABLE = 0;
  static final int[] STYLEABLE_ANIMATED_VECTOR_DRAWABLE_TARGET;
  @StyleableRes
  static final int STYLEABLE_ANIMATED_VECTOR_DRAWABLE_TARGET_ANIMATION = 1;
  @StyleableRes
  static final int STYLEABLE_ANIMATED_VECTOR_DRAWABLE_TARGET_NAME = 0;
  public static final int[] STYLEABLE_ANIMATOR;
  public static final int STYLEABLE_ANIMATOR_DURATION = 1;
  public static final int STYLEABLE_ANIMATOR_INTERPOLATOR = 0;
  public static final int STYLEABLE_ANIMATOR_REMOVE_BEFORE_M_RELEASE = 8;
  public static final int STYLEABLE_ANIMATOR_REPEAT_COUNT = 3;
  public static final int STYLEABLE_ANIMATOR_REPEAT_MODE = 4;
  public static final int[] STYLEABLE_ANIMATOR_SET;
  public static final int STYLEABLE_ANIMATOR_SET_ORDERING = 0;
  public static final int STYLEABLE_ANIMATOR_START_OFFSET = 2;
  public static final int STYLEABLE_ANIMATOR_VALUE_FROM = 5;
  public static final int STYLEABLE_ANIMATOR_VALUE_TO = 6;
  public static final int STYLEABLE_ANIMATOR_VALUE_TYPE = 7;
  public static final int[] STYLEABLE_KEYFRAME;
  public static final int STYLEABLE_KEYFRAME_FRACTION = 3;
  public static final int STYLEABLE_KEYFRAME_INTERPOLATOR = 1;
  public static final int STYLEABLE_KEYFRAME_VALUE = 0;
  public static final int STYLEABLE_KEYFRAME_VALUE_TYPE = 2;
  public static final int[] STYLEABLE_PATH_INTERPOLATOR = { 16843772, 16843773, 16843774, 16843775, 16843781 };
  public static final int STYLEABLE_PATH_INTERPOLATOR_CONTROL_X_1 = 0;
  public static final int STYLEABLE_PATH_INTERPOLATOR_CONTROL_X_2 = 2;
  public static final int STYLEABLE_PATH_INTERPOLATOR_CONTROL_Y_1 = 1;
  public static final int STYLEABLE_PATH_INTERPOLATOR_CONTROL_Y_2 = 3;
  public static final int STYLEABLE_PATH_INTERPOLATOR_PATH_DATA = 4;
  public static final int[] STYLEABLE_PROPERTY_ANIMATOR;
  public static final int STYLEABLE_PROPERTY_ANIMATOR_PATH_DATA = 1;
  public static final int STYLEABLE_PROPERTY_ANIMATOR_PROPERTY_NAME = 0;
  public static final int STYLEABLE_PROPERTY_ANIMATOR_PROPERTY_X_NAME = 2;
  public static final int STYLEABLE_PROPERTY_ANIMATOR_PROPERTY_Y_NAME = 3;
  public static final int[] STYLEABLE_PROPERTY_VALUES_HOLDER;
  public static final int STYLEABLE_PROPERTY_VALUES_HOLDER_PROPERTY_NAME = 3;
  public static final int STYLEABLE_PROPERTY_VALUES_HOLDER_VALUE_FROM = 0;
  public static final int STYLEABLE_PROPERTY_VALUES_HOLDER_VALUE_TO = 1;
  public static final int STYLEABLE_PROPERTY_VALUES_HOLDER_VALUE_TYPE = 2;
  static final int STYLEABLE_VECTOR_DRAWABLE_ALPHA = 4;
  static final int STYLEABLE_VECTOR_DRAWABLE_AUTO_MIRRORED = 5;
  static final int[] STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH;
  static final int STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH_NAME = 0;
  static final int STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH_PATH_DATA = 1;
  static final int[] STYLEABLE_VECTOR_DRAWABLE_GROUP;
  static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_NAME = 0;
  static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_PIVOT_X = 1;
  static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_PIVOT_Y = 2;
  static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_ROTATION = 5;
  static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_SCALE_X = 3;
  static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_SCALE_Y = 4;
  static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_TRANSLATE_X = 6;
  static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_TRANSLATE_Y = 7;
  static final int STYLEABLE_VECTOR_DRAWABLE_HEIGHT = 2;
  static final int STYLEABLE_VECTOR_DRAWABLE_NAME = 0;
  static final int[] STYLEABLE_VECTOR_DRAWABLE_PATH;
  static final int STYLEABLE_VECTOR_DRAWABLE_PATH_FILL_ALPHA = 12;
  static final int STYLEABLE_VECTOR_DRAWABLE_PATH_FILL_COLOR = 1;
  static final int STYLEABLE_VECTOR_DRAWABLE_PATH_NAME = 0;
  static final int STYLEABLE_VECTOR_DRAWABLE_PATH_PATH_DATA = 2;
  static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_ALPHA = 11;
  static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_COLOR = 3;
  static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_LINE_CAP = 8;
  static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_LINE_JOIN = 9;
  static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_MITER_LIMIT = 10;
  static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_WIDTH = 4;
  static final int STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_END = 6;
  static final int STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_FILLTYPE = 13;
  static final int STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_OFFSET = 7;
  static final int STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_START = 5;
  static final int STYLEABLE_VECTOR_DRAWABLE_TINT = 1;
  static final int STYLEABLE_VECTOR_DRAWABLE_TINT_MODE = 6;
  static final int[] STYLEABLE_VECTOR_DRAWABLE_TYPE_ARRAY = { 16842755, 16843041, 16843093, 16843097, 16843551, 16843754, 16843771, 16843778, 16843779 };
  static final int STYLEABLE_VECTOR_DRAWABLE_VIEWPORT_HEIGHT = 8;
  static final int STYLEABLE_VECTOR_DRAWABLE_VIEWPORT_WIDTH = 7;
  static final int STYLEABLE_VECTOR_DRAWABLE_WIDTH = 3;
  
  static
  {
    STYLEABLE_VECTOR_DRAWABLE_GROUP = new int[] { 16842755, 16843189, 16843190, 16843556, 16843557, 16843558, 16843866, 16843867 };
    STYLEABLE_VECTOR_DRAWABLE_PATH = new int[] { 16842755, 16843780, 16843781, 16843782, 16843783, 16843784, 16843785, 16843786, 16843787, 16843788, 16843789, 16843979, 16843980, 16844062 };
    STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH = new int[] { 16842755, 16843781 };
    STYLEABLE_ANIMATED_VECTOR_DRAWABLE = new int[] { 16843161 };
    STYLEABLE_ANIMATED_VECTOR_DRAWABLE_TARGET = new int[] { 16842755, 16843213 };
    STYLEABLE_ANIMATOR = new int[] { 16843073, 16843160, 16843198, 16843199, 16843200, 16843486, 16843487, 16843488, 17891484 };
    STYLEABLE_ANIMATOR_SET = new int[] { 16843490 };
    STYLEABLE_PROPERTY_VALUES_HOLDER = new int[] { 16843486, 16843487, 16843488, 16843489 };
    STYLEABLE_KEYFRAME = new int[] { 16842788, 16843073, 16843488, 16843992 };
    STYLEABLE_PROPERTY_ANIMATOR = new int[] { 16843489, 16843781, 16843892, 16843893 };
  }
}


/* Location:              /home/evan/Downloads/fugu-opr2.170623.027-factory-d4be396e/fugu-opr2.170623.027/image-fugu-opr2.170623.027/TVLauncher/TVLauncher/TVLauncher-dex2jar.jar!/android/support/graphics/drawable/AndroidResources.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */